// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/kms/v1/resources.proto

package com.google.cloud.kms.v1;

public interface ExternalProtectionLevelOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.kms.v1.ExternalProtectionLevelOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The URI for an external resource that this [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion] represents.
   * </pre>
   *
   * <code>string external_key_uri = 1;</code>
   * @return The externalKeyUri.
   */
  java.lang.String getExternalKeyUri();
  /**
   * <pre>
   * The URI for an external resource that this [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion] represents.
   * </pre>
   *
   * <code>string external_key_uri = 1;</code>
   * @return The bytes for externalKeyUri.
   */
  com.google.protobuf.ByteString
      getExternalKeyUriBytes();
}
